import Head from "next/head";
import { Inter } from "next/font/google";
import { api } from "@/utils/trpc";
import Notes from "@/components/Notes";
import { signIn, useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {data: session, status} = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="center">
        <h1 id="heading" className={`${inter.className} font-black text-5xl`}>
          This Is The Index Route
        </h1>
        <Notes />
        {session && session.user?.name}<button onClick={() => signIn("github")}>Sign In</button>
      </main>
    </>
  );
}
